# Generated by Django 5.0.3 on 2024-03-09 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("bio", models.TextField()),
                ("date_of_birth", models.DateField()),
                ("date_enrolled", models.DateField()),
                ("name_of_guardian", models.CharField(max_length=255)),
                ("is_prefect", models.BooleanField(default=False)),
                (
                    "gender",
                    models.CharField(choices=[("MALE", "Male"), ("FEMALE", "Female")]),
                ),
                (
                    "student",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("bio", models.TextField()),
                ("date_of_birth", models.DateField()),
                ("date_engaged", models.DateField()),
                (
                    "name_of_spouse",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[("SINGLE", "Single"), ("MARRIED", "Married")],
                        max_length=255,
                    ),
                ),
                (
                    "gender",
                    models.CharField(choices=[("MALE", "Male"), ("FEMALE", "Female")]),
                ),
                (
                    "tutor",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
                ("is_present", models.BooleanField(default=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="register.student",
                    ),
                ),
                (
                    "register_tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="register.tutor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_course", models.CharField(max_length=255)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_attending", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="register.student",
                    ),
                ),
                (
                    "course_tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="register.tutor"
                    ),
                ),
            ],
        ),
    ]
