# Generated by Django 5.0.3 on 2024-03-09 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_student_tutor"),
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyregister",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.student"
            ),
        ),
        migrations.AlterField(
            model_name="courseattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.student"
            ),
        ),
        migrations.RemoveField(
            model_name="tutor",
            name="tutor",
        ),
        migrations.AlterField(
            model_name="courseattendance",
            name="course_tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.tutor"
            ),
        ),
        migrations.AlterField(
            model_name="dailyregister",
            name="register_tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.tutor"
            ),
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="Tutor",
        ),
    ]
