# Generated by Django 5.0.3 on 2024-03-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_student_tutor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraActivities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("soccer", "Soccer"),
                            ("netball", "Netball"),
                            ("traditional dance", "Traditional Dance"),
                            ("tennis", "Tennis"),
                            ("athletics", "Athletics"),
                            ("swimming", "Swimming"),
                            ("hockey", "Hockey"),
                            ("rugby", "Rugby"),
                            ("baseball", "Baseball"),
                            ("boxing", "Boxing"),
                            ("handball", "Handball"),
                            ("wrestling", "Wrestling"),
                            ("public speaking", "Public Speaking"),
                            ("scripture union", "Scripture Union"),
                            ("basketball", "Basketball"),
                            ("javelin", "Javelin"),
                            ("short put", "Short Put"),
                            ("discus", "Discus"),
                            ("Not involved in any extra_curriculum activity", "None"),
                        ],
                        max_length=255,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=255,
                    ),
                ),
                ("student", models.ManyToManyField(to="accounts.student")),
                ("tutor_trainer", models.ManyToManyField(to="accounts.tutor")),
            ],
        ),
    ]
